version: 2

registries:
  jitpack-public:
    type: maven-repository
    url: https://jitpack.io
    username: "dummy"   # Satisfies Dependabot's strict requirement
    password: "dummy"   # JitPack will ignore this for public repos

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - jitpack-public
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.spigotmc:spigot-api"
        update-types: ["version-update:semver-major"]
