name: PotionGames
author: andersspielen
main: com.asga.potiongames.main.PotionGames
version: 4.9.6.1
api-version: 1.16
softdepend: [ Multiverse-Core, PlaceholderAPI ]
commands:
  pg:
    description: Get list of commands + permissions
    aliases: [ potiongames, pgames, potiong ]
