name: PotionGames
author: Tw0Far
main: com.tw0far.potiongames.main.PotionGames
version: 8.0.0
api-version: 1.21
softdepend: [ Multiverse-Core, Vault ]
commands:
  pg:
    description: Get list of commands + permissions
    aliases: [ potiongames, pgames, potiong ]